### ISSUE TITLE
How to test that?Could you give more details?

### ISSUE THREAD

**Issue by zychen2016** [golmschenk/sr-gan#1]

**Comment by zychen2016** [comment]
what is 'sgan'?
srgan -> semi supervised GAN for regression.

**Comment by golmschenk** [comment]
The sgan code is for a standard non-regression semi-supervised GAN. However, that portion of the code is not developed yet, and is not currently in a working form.

**Comment by meltemiatay** [comment]
Would you provide some details so I can replicate your results in one of the datasets, age data for example?
