### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by zychen2016** [golmschenk/sr-gan#2]
https://github.com/golmschenk/sr-gan/blob/a08b22fcce27c17b9a6ca9d62320425693dab67c/srgan.py#L26

**Comment by golmschenk** [comment]
Hi! Could you explain what you believe is a bug at this line? If this line itself is causing an error for you, you are likely using Python 2 which does not include type hinting (which is being used on this line). Python 3 is required. If you think something else is the problem, please elaborate.

**Comment by zychen2016** [comment]
Just run method_name = 'srgan',application_name='age'.

type python3 run.py, it will raise a error
![image](https://user-images.githubusercontent.com/23021461/50977049-5d535f00-152c-11e9-9bd8-686f7105d478.png)

**Comment by zychen2016** [comment]
python version:3.5.2, used in linux

**Comment by zychen2016** [comment]
You crop imdb_wiki_image to 128*128, have you try to larger size? 256*256?

**Comment by golmschenk** [comment]
Type hinting was added in Python 3.6, so you'll need to upgrade your Python version. As this is almost certainly the problem, I will close this issue.

For the image sizes, I have used various image sizes, and it should not be much work to modify the code for the different sizes.

Lastly, I should note, this project is a constantly changing research project, so things will often not work if you use the code in master. If you want something slightly more stable, I recommend you use the code on in the 0.1 release tag for now.

**Comment by zychen2016** [comment]
OK.I use 0.1 release.
However,When I first type python3 ./age/data.py, Then python3 run.py with `application_name="age"`,
```
FileNotFoundError: [Errno 2] No such file or directory: '../imdb_wiki_data/imdb_preprocessed_128/meta.json'
```
May be you should change that ?
Thank you!
