### ISSUE TITLE
raise TypeError("Cannot handle this data type") 

### ISSUE THREAD

**Issue by zychen2016** [golmschenk/sr-gan#3]
```
/data2/CZY/software/anconda2/envs/python36/lib/python3.6/site-packages/torch/nn/functional.py:995: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
/data2/CZY/software/anconda2/envs/python36/lib/python3.6/site-packages/torch/nn/functional.py:995: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Step 0, 0:00:06.675964...Traceback (most recent call last):
  File "/data2/CZY/software/anconda2/envs/python36/lib/python3.6/site-packages/PIL/Image.py", line 2490, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 392), '|u1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 73, in <module>
    experiment.train()
  File "/data2/CZY/SS_GAN/regression/sr-gan-0.1/srgan.py", line 112, in train
    validation_summaries(self, step)
  File "/data2/CZY/SS_GAN/regression/sr-gan-0.1/age/application.py", line 76, in validation_summaries
    gan_summary_writer.add_image('Real', images_image.numpy().transpose([1, 2, 0]).astype(np.uint8))
  File "/data2/CZY/SS_GAN/regression/sr-gan-0.1/utility.py", line 43, in add_image
    super().add_image(tag, img_tensor, global_step)
  File "/data2/CZY/software/anconda2/envs/python36/lib/python3.6/site-packages/tensorboardX/writer.py", line 427, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File "/data2/CZY/software/anconda2/envs/python36/lib/python3.6/site-packages/tensorboardX/summary.py", line 216, in image
    image = make_image(tensor, rescale=rescale)
  File "/data2/CZY/software/anconda2/envs/python36/lib/python3.6/site-packages/tensorboardX/summary.py", line 254, in make_image
    image = Image.fromarray(tensor)
  File "/data2/CZY/software/anconda2/envs/python36/lib/python3.6/site-packages/PIL/Image.py", line 2492, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
```

**Comment by zychen2016** [comment]
May be you should write readme about useage and package version .

**Comment by zychen2016** [comment]
Can you give me some suggestions?

**Comment by zychen2016** [comment]
I use your 0.2 tags.
```
git clone https://github.com/golmschenk/sr-gan/archive/0.2.tar.gz
tar -zxvf 0.2.tar.gz
cd sr-gan-0.2
#because I want to try sr-gan about age regression, so modify application_name='crowd' to 'age' in run.py
python3.6 run.py
```
However, still have some errors
1. 
![image](https://user-images.githubusercontent.com/23021461/51092973-f73f3400-17d8-11e9-9cc9-2495adb7bded.png)

Then I try to run /age/data.py first, after download the data, modify /age/srgan.py `dataset_path = ` to absolute path.

again, python3.6 run.py
![image](https://user-images.githubusercontent.com/23021461/51093004-46856480-17d9-11e9-85d9-16ed582cb962.png)

so, Could you full test your  code from download data?
Because if i run run.py first, It would'nt download age data. Only when I run /age/data.py, It will download data.
Then, could you write a readme file about how to use your codes?

Thank you very much!

**Comment by golmschenk** [comment]
It seems the age application was not setup to handle `None` as the size of the unlabeled dataset. To fix the last error you listed, in `run.py` try changing `settings_.unlabeled_dataset_size = None` to `settings_.unlabeled_dataset_size = 10000`.

**Comment by zychen2016** [comment]
Another error
![image](https://user-images.githubusercontent.com/23021461/51362779-e875bb80-1b0f-11e9-9760-2c82ba66955d.png)

(python36) user@user:/data2/CZY/SS_GAN/regression/sr-gan-0.2$ conda list
# packages in environment at /data2/CZY/software/anconda2/envs/python36:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5           py36he75722e_1  
cloudpickle               0.6.1                      py_0    conda-forge
cudatoolkit               9.0                  h13b8566_0  
cudnn                     7.1.2                 cuda9.0_0  
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1          py36h470a237_1    conda-forge
dask-core                 1.0.0                      py_0    conda-forge
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                      py_0    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h8a8886c_1  
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
glib                      2.56.2               h464dc38_1    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
icu                       58.2                 hfc679d8_0    conda-forge
imageio                   2.4.1                    py36_0  
intel-openmp              2019.1                      144  
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15                 h470a237_4    conda-forge
libopenblas               0.3.3                h5a2b251_3  
libpng                    1.6.35               hbc83047_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.9                he85c1e1_2  
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
matplotlib                3.0.2            py36h8a2030e_1    conda-forge
matplotlib-base           3.0.2            py36h20b835b_1    conda-forge
matplotlib2tikz           0.6.18                     py_0    conda-forge
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6            py36h7dd41cf_0  
mkl_random                1.0.1            py36h629b387_0  
nccl                      1.3.5                 cuda9.0_0  
ncurses                   6.1                  he6710b0_1  
networkx                  2.2                        py_1    conda-forge
ninja                     1.8.2            py36h6bb024c_1  
numpy                     1.15.4           py36h1d66e8a_0  
numpy-base                1.15.4           py36h81de0dd_0  
olefile                   0.46                     py36_0  
openssl                   1.0.2p            h14c3975_1002    conda-forge
pandas                    0.23.4           py36h04863e7_0  
patool                    1.12             py36ha7d2b2a_0    farrajota
patsy                     0.5.1                    py36_0  
pcre                      8.42                 h439df22_0  
pillow                    5.4.1           py36h00a061d_1000    conda-forge
pip                       18.1                     py36_0  
protobuf                  3.6.1                     <pip>
pthread-stubs             0.4                  h470a237_1    conda-forge
pycparser                 2.19                     py36_0  
pyparsing                 2.3.0                      py_0    conda-forge
pyqt                      5.6.0            py36h8210e8a_8    conda-forge
python                    3.6.7             hd21baee_1001    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytorch                   0.4.0            py36hdf912b8_0  
pytz                      2018.7                   py36_0  
pywavelets                1.0.1            py36h7eb728f_0    conda-forge
qt                        5.6.3                h8bf5577_3  
readline                  7.0                  h7b6447c_5  
scikit-image              0.14.1           py36hfc679d8_4    conda-forge
scikit-learn              0.20.1           py36h4989274_0  
scipy                     1.1.0            py36hfa4b5c9_1  
seaborn                   0.9.0                    py36_0  
setuptools                40.6.3                   py36_0  
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.12.0                   py36_0  
sqlite                    3.26.0               h7b6447c_0  
statsmodels               0.9.0            py36h035aef0_0  
tensorboardX              1.6                       <pip>
tk                        8.6.9             h84994c4_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
torchvision               0.2.1                    py36_0  
tornado                   5.1.1            py36h470a237_0    conda-forge
wheel                     0.32.3                   py36_0  
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3
