### ISSUE TITLE
Age dataset

### ISSUE THREAD

**Issue by meredith92** [golmschenk/sr-gan#7]
Could I know how could I get the meta.json data for age training ?

**Comment by golmschenk** [comment]
Each of the datasets should have a corresponding Python file related to the data, which when run should download and preprocess the dataset. So for the age dataset, you can run `python -m age.data` from the repository directory to download and prepare the dataset.

However, this assumes the groups that host the data still have the data available at the same URLs they were at when I originally wrote this code.
