### ISSUE TITLE
meta.pkl is missing

### ISSUE THREAD

**Issue by cloverzyy** [golmschenk/sr-gan#8]
Hi, it's an interesting work! I'm trying to run your code. Where can I download the "meta.pkl"? The download link is not mentioned in the code or comments in driving/data.py.

**Comment by golmschenk** [comment]
Hello! In the `driving/data.py` file, the `preprocess` method creates the `meta.pkl` file. The `driving/data.py` file should automatically download and prepare the full dataset. However, it appears the dataset maintainer no longer uses the Google drive link currently in the code. The updated links can be found on the dataset maintainer's repository: https://github.com/SullyChen/driving-datasets

**Comment by cloverzyy** [comment]
这是来自QQ邮箱的假期自动回复邮件。来信已收到，辛苦各位啦！
